PROGRAM test;

BEGIN
     ClrScr;
     Writeln('*******************Speed-386 fÅr OS/2********************');
     Writeln;
     Writeln('Diese Zeile wurde mittels eines PASCAL-WriteLn Befehls dargestellt !');
     Writeln('Textmodus Programme laufen also unter OS/2 im PM-Fenster !');
     Writeln;
     Writeln('Bitte eine Taste drÅcken !!');
     ReadKey;
     Writeln;
     Writeln('Um zu beenden schlie·en Sie das PM-Fenster !');
END.





